name: cs_galaxies
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib
  - tqdm
  - pandas
  - pandasql
  - astropy
  - fastparquet
  - astroquery
  - sklearn
  - sqlalchemy # db interface
  - psycopg2 # posgreSQL driver
